AzNamingTool - revert registering state.OnChange, breaks thread context
System.InvalidOperationException: The current thread is not associated
with the Dispatcher. Use InvokeAsync() to switch execution to the
Dispatcher when triggering rendering or component state.

todo: investigate and clean up state onchange cruft, this is a quick fix